# Generated by Django 3.2.7 on 2021-09-07 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contatos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('numeto', models.CharField(max_length=17)),
            ],
        ),
        migrations.DeleteModel(
            name='Arquivos',
        ),
    ]
