# Generated by Django 3.2.7 on 2021-09-07 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210907_1158'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contatos',
            old_name='numeto',
            new_name='numero',
        ),
    ]
